#!/usr/bin/env bash
# Sets up the Instagram Content Bot:
#   1. Python venv + dependencies
#   2. .env file (prompts for keys)
#   3. Installs systemd service (Linux) or launchd plist (macOS) for 10pm PT run

set -e
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENV="$SCRIPT_DIR/.venv"
SERVICE_NAME="instagram-content-bot"

echo ""
echo "╔══════════════════════════════════════════════════════╗"
echo "║        @gobi_automates — Instagram Content Bot       ║"
echo "╚══════════════════════════════════════════════════════╝"
echo ""

# ── 1. Python venv ────────────────────────────────────────────────────────────
echo "→ Creating Python virtual environment..."
python3 -m venv "$VENV"
# shellcheck disable=SC1091
source "$VENV/bin/activate"
pip install --upgrade pip --quiet
pip install -r "$SCRIPT_DIR/requirements.txt" --quiet
echo "  ✓ Dependencies installed"

# ── 2. .env ───────────────────────────────────────────────────────────────────
if [ ! -f "$SCRIPT_DIR/.env" ]; then
    echo ""
    echo "→ Setting up .env credentials..."
    echo "  (Get Anthropic key from https://console.anthropic.com/settings/api-keys)"
    read -rp "  Anthropic API key: " ANTHROPIC_KEY
    echo ""
    echo "  Instagram scraping works best with a BURNER account (not @gobi_automates)."
    echo "  Leave blank to run anonymously (heavily rate-limited after ~5 profiles)."
    read -rp "  Burner IG username (or press Enter to skip): " IG_USER
    read -rsp "  Burner IG password (or press Enter to skip): " IG_PASS
    echo ""

    cat > "$SCRIPT_DIR/.env" <<EOF
ANTHROPIC_API_KEY=$ANTHROPIC_KEY
IG_USERNAME=$IG_USER
IG_PASSWORD=$IG_PASS
EOF
    echo "  ✓ .env saved"
else
    echo "  ✓ .env already exists — skipping"
fi

# ── 3. Run wrapper ────────────────────────────────────────────────────────────
RUN_SH="$SCRIPT_DIR/run.sh"
cat > "$RUN_SH" <<RUNEOF
#!/usr/bin/env bash
# Auto-generated by setup.sh — do not edit manually
set -e
source "$VENV/bin/activate"
cd "$SCRIPT_DIR"
exec python main.py --daemon
RUNEOF
chmod +x "$RUN_SH"
echo "  ✓ run.sh created"

# ── 4. Scheduler (systemd or launchd) ────────────────────────────────────────
echo ""
if command -v systemctl &>/dev/null && [ "$(uname)" = "Linux" ]; then
    SERVICE_FILE="$HOME/.config/systemd/user/$SERVICE_NAME.service"
    mkdir -p "$(dirname "$SERVICE_FILE")"
    cat > "$SERVICE_FILE" <<EOF
[Unit]
Description=Instagram Content Bot — @gobi_automates (fires at 22:00 PT)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=$RUN_SH
Restart=on-failure
RestartSec=60
Environment=TZ=America/Los_Angeles

[Install]
WantedBy=default.target
EOF
    systemctl --user daemon-reload
    systemctl --user enable --now "$SERVICE_NAME"
    echo "  ✓ systemd user service installed and started"
    echo "    Status: systemctl --user status $SERVICE_NAME"
    echo "    Logs:   journalctl --user -u $SERVICE_NAME -f"

elif [ "$(uname)" = "Darwin" ]; then
    PLIST_PATH="$HOME/Library/LaunchAgents/com.gobi_automates.instagram-bot.plist"
    cat > "$PLIST_PATH" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.gobi_automates.instagram-bot</string>
    <key>ProgramArguments</key>
    <array>
        <string>$RUN_SH</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>StandardOutPath</key>
    <string>$SCRIPT_DIR/output/launchd.log</string>
    <key>StandardErrorPath</key>
    <string>$SCRIPT_DIR/output/launchd_error.log</string>
    <key>EnvironmentVariables</key>
    <dict>
        <key>TZ</key>
        <string>America/Los_Angeles</string>
    </dict>
</dict>
</plist>
EOF
    launchctl load "$PLIST_PATH"
    echo "  ✓ macOS LaunchAgent installed"
    echo "    Logs: tail -f $SCRIPT_DIR/output/launchd.log"
else
    echo "  ⚠ Could not detect systemd or launchd."
    echo "    Add this to your cron (fires at 22:00 PT = 06:00 UTC):"
    echo "    0 6 * * * TZ=America/Los_Angeles $RUN_SH >> $SCRIPT_DIR/output/cron.log 2>&1"
fi

echo ""
echo "╔══════════════════════════════════════════════════════╗"
echo "║  Setup complete! Bot fires at 10:00 PM PT every day  ║"
echo "║                                                      ║"
echo "║  Next steps:                                         ║"
echo "║  1. Edit competitors.json with real IG handles       ║"
echo "║  2. Test now: python main.py                         ║"
echo "║  3. CRM lands in: output/ folder                     ║"
echo "╚══════════════════════════════════════════════════════╝"
echo ""
